---
- name: Setup apache2 server
  hosts: planetexpress
  gather_facts: no
  connection: ssh
  become: yes

  #roles:
  #        - base-apache-server
  #
  tasks:
          - name: Import a role to run
            import_role: 
                name: base-apache-server

          - name: Just a simple task as an example
            debug:
                    msg: "This will run last"
