---
 - name: Looping old-style with_items
   hosts: localhost
   gather_facts: no

   tasks:
    - name: "Learning about the debug module"
      debug:
        msg: "Debug module allows us to print to the screen --> {{ item }}"
      with_items:
      - "255.255.255.0"
      - "192.168.0.1"
      - "192.168.0.2"

