---
- name: Import vs include
  hosts: all
  gather_facts: yes

  tasks:
            #- name: include (DYNAMIC) POST PROCESSING WORKS
            #include_tasks: "{{ ansible_os_family }}.yml"

            - name: import (STATIC) PRE PROCESSING FAILS (facts not yet gathered)
              import_tasks: "{{ ansible_os_family }}.yml"


