---
- name: Playbook that runs a Perl script
  hosts: localhost

  tasks:
  - name: Copy script to target hosts and execute it
    script: ~/ans/scripts/starWars.pl
    args:
      executable: /usr/bin/perl
    register: results    # save the JSON sent back by our script

  - name: Print out the 'results'
    debug:
      var: results
      # notice there is a stdout and stdout_lines

